[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "json_schemas"
authors = [{name = "Keith", email = "keith.franklin@gmail.com"}]
dynamic = ["version", "description"]